[project]
name = "hackathon"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "folium>=0.20.0",
    "geopandas>=1.1.1",
    "marimo>=0.17.0",
    "openpyxl>=3.1.5",
    "polars>=1.34.0",
]
